### ISSUE TITLE
Breaking "zfs send" compatibility by activating the feature large_dnode on the rpool

### ISSUE THREAD

**Issue by satoshishop** [ubuntu/zsys#107]
**Describe the bug**
When you zfs send from your rpool to a zfs pool that did not implement large_dnode, the transfer gets canceled with the error: "**cannot receive: stream has unsupported feature, feature flags = 800004**"

**To Reproduce**
1. zfs-send (zfs send rpool/dataset@snapshot | ssh root@remotehost zfs recv -F tank/dataset) to a zpool on one of these distros.

- FreeBSD (11.2.0, 11.3.0, 12.0.0 and head)
- DragonFlyBSD (zfsport)
- NetBSD (main)
- OmniOSCE (r151028)

**Additional context**
**The large_dnode feature becomes active once a dataset contains an object with a dnode larger than 512B**, which occurs as a result of **setting the dnodesize dataset property to a value other than legacy**. The feature will return to being enabled once all filesystems that have ever contained a dnode larger than 512B are destroyed.

**Comment by satoshishop** [comment]
Why did you change the dnodesize value from legacy to auto? This enabled the pool to create dnodes lager than 512B

**Comment by satoshishop** [comment]
Left side: my proxmox machine with perfectly working zfs send functionality
right side: my kubuntu system with unsupported feature error

https://kopano.mariokuschel.info/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1471&y=1212&a=true&file=zsys_large_dnode.png&t=3MyVaVApX6jKzPs&scalingup=0

**Comment by satoshishop** [comment]
ZFS-Feature states
 Features can be in one of three states:

 active    This feature's on-disk format changes are in effect on the
       pool.  Support for this feature is required to import the pool
       in read-write mode.  If this feature is not read-only compati-
       ble, support is also required to import the pool in read-only
       mode (see "Read-only compatibility").

 enabled   An administrator has marked this feature as enabled on the
       pool, but the feature's on-disk format changes have not been
       made yet.  The pool can still be imported by software that does
       not support this feature, but changes may be made to the
       on-disk format at any time which will move the feature to the
       active state.  Some features may support returning to the
       enabled state after becoming active.  See feature-specific doc-
       umentation for details.

 disabled  This feature's on-disk format changes have not been made and
       will not be made unless an administrator moves the feature to
       the enabled state.  Features cannot be disabled once they have
       been enabled.

**Comment by didrocks** [comment]
**dnodesize** is set to auto on the upstream ZFS On Linux recommendation for installing zfs on root on Ubuntu 18.04 and we are following those guidelines:
https://github.com/openzfs/zfs/wiki/Ubuntu-18.04-Root-on-ZFS

Maybe this is some defaults that we can discuss with @rlaager?

**Comment by rlaager** [comment]
Upstream ZFS enables all features by default on pool creation. The HOWTO and Ubuntu installer inherit this behavior. This behavior is consistent with other filesystems (e.g. ext4, which had some compatibility concern on IIRC 18.04). I believe this is the right default.

I do recognize that compatibility is more of a concern with ZFS than other filesystems because of `zfs send`. I wouldn’t be against a checkbox/drop-down in the installer to trade-off compatibility vs latest features. (I believe we have talked about this before.) Originally, I was thinking about this in terms of the proposed `features=portable` concept. (Unfortunately, nobody is actively working on that. Maybe Ubuntu could do that or could sponsor someone?) Otherwise, the installer could keep a features mask itself. For example, it could offer a drop-down for compatibility with the various still-supported Ubuntu releases, and maybe even one for “most platforms” or something.

**Comment by didrocks** [comment]
Thanks Richard! I am closing this one thus (anyway, this isn‘t related to zsys, but more on the installer). The installer will grow options in the future and we will develop a way to tweak settings in incoming blog posts on planet ubuntu.
