### ISSUE TITLE
apt install/upgrades should not result in user area snapshots

### ISSUE THREAD

**Issue by MarcusEbert** [ubuntu/zsys#162]
Linux mint 20
zsysd 0.4.7
ZFS used for root and userdata
(rpool/ROOT and rpool/USERDATA)

Issue: Currently, whenever there is a new version of a program installed, zsys is doing a snapshot for all zfs  under rpool.
However, it seems not of much use to do so for rpool/USERDATA since
1) a rollback to get a previous state in case of problematic tools, e.g. at boot time,  is only useful for rpool/ROOT but should never be done for rpool/USERDATA since users data in $HOME is completely independent of system files and such behavior can lead to data lost, especially in case of a multi-user system where one user decides to reboot and to rollback system+user filesystems. 
2) rpool can fill up quickly when there are often large changes in the user's home directories with frequent install of new programs or updates happening. In that case a user can't free up space by deleting files in their own area since the snapshots occupy the whole space. Due to sharing rpool space between rpool/ROOT and rpool/USERDATA this is also an issue for general system operation since it also reduces the free space available for /var/log or /tmp.

Suggestion: Decouple snapshots for rpool/ROOT and rpool/USERDATA completely.
system installs/changes should only result in and monitor rpool/ROOT while users should do and manage snapshots of their own  zfs area under rpool/USERDATA.

I couldn't find any configuration files for zsysd. If there is one and the above is already possible, e.g. via specifying which zfs' should be snapshot in case of system changes, please see this as solved and I would appreciate to get pointed to the right place to make such config changes in the system.

**Comment by didrocks** [comment]
hey,

This is done on purpose, to ensure that a system revert will *always* revert you to a coherent state. You can have application data that changed format and upgraded your database. If we didn’t snapshot USERDATA, then, reverting the system will end up in, for instance, older thunderbird not being able to open the new database schema (it can’t know about it), and so, your system snapshot will be useless.

There is no point in snapshotting only the system thus. I suggest that you read this blog post which details that a little bit more: https://didrocks.fr/2020/05/28/zfs-focus-on-ubuntu-20.04-lts-zsys-general-principle-on-state-management/.

I don’t think we want to allow for this kind of configuration, or we will have afterthat puzzled users which did some settings change and won’t understand or will be upset that they can’t revert due to those kinds of real-world issues.

I’m closing this bug for now then, hoping that made it clear :)

**Comment by MarcusEbert** [comment]
Hi and thanks for the answer!

I see the point you are making but there is a problem in any case:
1) if you do not snapshot all ZFSs you can not roll back to a consistent state as you mentioned
2) if you do snapshot and roll back all ZFSs incl. USERDATA then at rollback all new personal user data will be lost

In the first case, a system snapshot will not be useless since it will allow the OS to function well again in case of troubles after an upgrade, e.g. new kernel. Not all programs may function well however as you mentioned, but that can be fixed by Users themselves, e.g. by rebuilding the thunderbird db or upgrading to a newer thunderbird only. Also this only happens IF such programs are there that are not compatible between versions. But in any case, there is no data loss at all but data may not be accessible until an upgrade of specific programs.

The second case however,  will result in real data loss for sure when USERDATA is rolled back,  user data like new documents or code will be lost. 

I can see your point to prefer a snapshot of everything and to rollback to a consistent overall state, but this may be more dangerous than having just some programs not working well until they are upgraded.  In any case, there may be use cases where one or the other is creating more destruction than good - could this be added as a configuration option somewhere maybe if one wants to do such snapshots for USERDATA too or not?

Chees,
 Marcus

**Comment by didrocks** [comment]
Hey Marcus,

We snapshot all ZFS datasets that are not persistent, the persistent datasets are datasets selected explicitely by the user to be backward and forward compatible (there is none by default).
Indeed, if you select the option to revert, including USERDATA, every new changes is lost (actually no, see below), but, there is the option as well to revert without selecting USERDATA.
Contrary to a zfs rollback, we don’t destroy intermediate states, and so, even if you revert with USERDATA, you can still access to the latest version of your data (manually right now).

This allows you as well to revert the revert! This is how we designed the whole system to take all those considerations into account. The additional space taken by snapshotting user snapshots it minimum, because remember that we do hourly user snapshots anyway for any connected users. As the snapshots will only contains the diff, the amount of space taken will be the same in the end.

I strongly encourage you to read the whole blog post suite on https://didrocks.fr where I try to explain all those concepts and why those choices if you still wonder about it :)
