### ISSUE TITLE
Ran out of space (couldn't even boot)

### ISSUE THREAD

**Issue by Saviq** [ubuntu/zsys#61]
I'm on a small-ish 128GB `RPOOL` with roughly half of it used, but with relatively significant churn on the remaining space. The result was that snapshots took the remaining half of the pool for me and the system basically caught fire.

Part of the problem is that we seem to have lost the 5% space reservation for root when using ZFS - not sure if it's even possible to enforce, though.

Another part is that `zsys` does not seem to take disk space into account when expiring snapshots.

A [`zsys show`](https://github.com/ubuntu/zsys/files/4329640/zsys-show.txt) from Tuesday shows there were a bunch of snapshots already.

Yesterday, when I ran out of space, I took [`zfs list`](https://github.com/ubuntu/zsys/files/4329636/zfs-list.txt) and [`zfs list -t snapshot`](https://github.com/ubuntu/zsys/files/4329637/zfs-list-snapshot.txt) - the snapshot list does not seem to have the real space usage listed, as can be seen by comparing to `USEDSNAP` for a dataset.

Some suggestions:
- take available disk space into consideration when expiring snapshots
- include real snapshot disk usage info in `zsysctl show`
- allow for purging of snapshots in `zsysctl`

**Comment by richardelling** [comment]
Reservations do work, but that doesn't protect against the non-reserved datasets running out of space.
Methinks you're advocating quotas, which is a whole other discussion.

**Comment by didrocks** [comment]
After a lot of thoughts and testing on real world system, we really can’t pressurize the GC to collect more snapshots without impacting the users. Especially in VM cases, this will grow up to take all snapshots as we have dangling kernels in particular left here.

Unfortunately, as the history is non linear, there is no easy way to include real snapshot disk usage by snapshots (even upstream ZFS doesn’t have any facilities to that because it’s complex): the real take is "you should combine snapshots to free space, not only one". If you look at the USE size of a snapshots, you will indeed see very little space that can be taken by only removing on snapshot, as most of the space is common between multiple of them.
So, it’s not an individual snapshots that need to take into account, but a range (including its dependencies).

We decided thus to attack that in multiple steps:
- https://github.com/ubuntu/zsys/pull/115 prevents taking automatically or manually any more snapshots when reaching the edge of ZFS performance high limit (this is tweakable). It will error out. Future releases should signal that to the client (issue #120)
- a reclaim commands to analyzes all snapshots, for big space and what the optimal removal path would be, borning by times (issue #121).
- this will then be included in existing `zsysctl state remove` command, which will grow options for borning in times.

I’m closing thus this bug as, at least, zsys can’t file your disk automatically out of space anymore.

There is still a separate issue that GRUB doesn’t boot when disk is full which is filed on launchpad as https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1867542
