### ISSUE TITLE
Boot fails (maintenance mode) when device names change

### ISSUE THREAD

**Issue by lathiat** [ubuntu/zsys#98]
### Issue
On my system the NVMe device names frequently change name, in such a case the system will fail to boot as the 'bpool' pool does not import (even though rpool does).

I'm creating this as a catch-all bug as there are a number of possible solutions, which may then fan out into bugs again zsys, zfsonlinux or the installer based on the discussion.

### Reproduction Details
Tested using the focal-daily-live from April 16.

For the avoidance of confusion the specific problem I have is that 'nvme0' which is not in use randomly appears and disappears. nvme1 (linux) and nvme2 (windows) sometimes are thus shuffled down to nvme0 and nvme1. However the problem of devices renaming is an age-old problem that is mostly solved in other areas and it's generally accepted we should try not to rely on them.

And in my specific case the first boot after reboot from install failed.

### Details
Firstly the actual problem I hit is that on boot, bpool fails to import (but rpool is imported, and the root filesystem is mounted). This stops the boot from proceeding with a systemd error and a message to hit enter to enter maintenance mode.

In syslog we get

> Apr 16 14:39:58 optane kernel: [    6.641111] ERROR: zfs-mount-generator failed and you requested a revert:
> Apr 16 14:39:58 optane kernel: [    6.641395] cannot import 'bpool': no such pool or dataset
> Apr 16 14:39:58 optane kernel: [    6.641395]   Destroy and re-create the pool from
> Apr 16 14:39:58 optane kernel: [    6.641395]   a backup source.
> Apr 16 14:39:58 optane kernel: [    6.641461] You can reboot on current master dataset to fix the issue
> Apr 16 14:39:58 optane kernel: [    6.641528] systemd[724]: /usr/lib/systemd/system-generators/zfs-mount-generator failed with exit status 1.

You can workaround this by running "zpool import -a" and then exiting the shell to continue boot. (in fact mounting the pool is not technically necessary, you can just exit).

The reason the import fails appears to be because the device names in /etc/zfs/zpool.cache are using /dev/nvme* which on my system changes between boots instead of a persistent path such as /dev/disk/by-*.

For whatever reason the root pool always imports regardless I am not entirely sure why. My assumption is that the code responsible for the root=ZFS= handling attempts it's own import outside of the zfsutils-linux systemd hooks but I'm not really sure. I couldn't locate the code that handles that, I assumed it was an initramfs-tools hook in the initramfs but I couldn't actually locate the code doing that - can someone point me to it?

This causes a flow on issue that may need some independent fixing
 (1) boot.mount fails which causes boot-efi.mount and boot-grub.mount to fail. /boot may fail to mount due to existing files in it's place. That means I get a system that boots, but, update-grub doesn't work and kernel upgrades aren't written into the right place. You get 'stuck' at the current kernel/grub menu which is confusing even though 'update-grub' runs and works just outputs it's files into /boot on the rpool. This seems related to #60. I think we need some better safe-guarding for this issue in general as it has multiple possible causes and leads to a very confusing boot debug experience. This seemed to sometimes happen even when the system booted cleanly presumably due to the existing files issue. Probably we need to consider overlay=on for the bpool to make this situation less likely even though it will possibly hide an underlying issue.

Some further thoughts
(2) Ideally pools would be created using persistent device names (/dev/disk/by-*) instead of direct device names (/dev/nvme*). Although the choice of "which" has some arguments. You can change this name by exporting and importing a pool again, though, that is difficult to do for the root pool.

(3) The rpool seems to get imported regardless probably based on how the initramfs for that script is working. Since we have 2 pools that are required for the system we may need to look at improving the logic around both bpool and rpool in some way. For example if both rpool and bpool don't both import, perhaps we should consider a backup import-scan for these 2 pools. This does raise potential issues where you have 2 such pools in a system, but if we rely on this as a backup that's probably a good start.. and currently since we use root=ZFS=zpool/xxx I suspect it relies on a pool name anyway (although I was having trouble finding where that code is)

Apologies for the long issue, as above, I'm happy to split out into new issues each part but I sortof wanted to discuss the general case first. Though I left it for completeness I will open a new bug for (1) above and then my thought is that we can probably solve both (2) and (3) independently as insurance against both the general and backup case? But I'd love your feedback on whether either of them are non-starter ideas for some reason I have not envisaged.

- Trent "@lathiat" (Sustaining Engineering, Canonical)

**Comment by didrocks** [comment]
Thanks for this detailed bug report! Here are some thoughts and some actions we can tackle:

* Changing devices name -> waow, first time I heared about that, especially as systemd moved to well-known device name for a while and I thought we can support it I’m surprised nothing else is failing on those disappearing devices which then, ofc renames others).
Anyway, the `bpool.cache` importing by device name is an issue in openzfs itself. Do you mind opening a bug there and suggest importing by uuid or see what’s their interests are? (I think this cover the intro and (2)).
At the same time, another issue I’m seeing is when people having multiple pools with a similar name, as their generator is using the pool name as an identifier in `/etc/zfs/zfs-list.cache`, generates the systemd `.mount` files, however systemd then is using the mount command directly relying on existing imported pools.

(1) -> systemd was booting first without any warning when the generator failed, this is why we added the safeguard by dropping you in emergency mode in that case. You are correct thus that unfortunately, the boot can resume and people can house their system. I don’t really like the idea of allowing overlay as it means you booted in a broken stage without noticing. I think we should really prevent the boot at first.
The emegency mode was the first step. I wonder really how we can stop the boot, ensuring that missing bpool is a real issue and not:
- a non zfs system (easy to detect by /proc/cmdline)
- an user configured system who has another boot pool or no separated boot pool at all
Do you have any idea on this? Stopping systemd early and be sure we are in that case while the system will be broken (the issue is that no pool is imported in the generator yet and the idea is to create the minimal amount of work there before the system is starting up. Also, failing the generator doesn’t fail the boot).
I think most of this can be worked on with upstream, as the systemd generator is a new feature in 0.8. We only added more safeguards and supported revert as distro-patches. I think we are the first distro to enable the generator and they didn’t see those issues (especially as /boot/grub is in fstab for us, but if you don’t have that prerequisite missing bpool at boot is masked by their zfs-mount.service later in the boot).
Note that if systemd didn’t create the missing directories (like /boot/grub), then it would fail the boot and preventing housing your system…
Happy to iterate on this with you so that we can find a robust solution to bring to them (but that doesn’t prevent opening a discussion with them first)

(3) the rpool is indeed imported by the initramfs upstream zfs script. grub indicates which devices (by id) to import and this is why you are seeing it after pivot_root on the system to be correctly imported. If you are interested, you will find it at `/usr/share/initramfs-tools/scripts/zfs`.
The issue is that again, we still want people having their own ZFS installation to be supported (non zsys one), or those who want to convert their layout to a zsys one without having necessarilly a bpool (there is nothing apart the installer that assumes/forces a bpool).
We should try to see how we can tackle those without adding too much delta with the upstream initramf script (we only have a few changes for zsys cases).
That’s true that if we solve (3) in initramfs, we can fail the boot really early (but how to recover then?). I would prefer though that we try to fail the boot rather just after the systemd generator in (1)/(2), that means in `local-fs.target` so that we prevent incorrect boot and work with upstream on having something based on a more stable name for importing in bpool.cache.

I think none of those tasks is directly related to zsys itself, but I’m happy that we keep it there for tracking it. Tell me if what I say makes sense, if you need help to open the upstream bugs and if you have any idea on how we can protect ourselves so that we iterate together on this!

No worry on the long bug, it’s detailed and really informative, which is always appreciated :)

**Comment by didrocks** [comment]
jilbel has an idea: maybe when we `zpool create` in the installer, we could try to use the uuid and *maybe* zpool.cache would have the right device name. Something we need to check (we are unfortunately in final freeze for 20.04 but we may fix it before 20.04.1). We’ll test it shortly. This means that there is no need for bug on zfs upstream for this zpool.cache

There are still the other opened questions about failing boot though.

**Comment by ofthesun9** [comment]
I was hit by this issue few days ago:
I connected an (external) drive to attach a zpool, which also triggered a dev change for  bpool & rpool
Thanks to this PR, I could solve the issue. 
I recognize that my use case is a liitle bit exotic (my "zpool and bpool" drive is also on an external drive), but this could be useful for others :-)

**Comment by jibel** [comment]
Distro bug https://bugs.launchpad.net/bugs/1880869

**Comment by jibel** [comment]
pushed upstream https://git.launchpad.net/ubiquity/commit/?id=36ea45160d00c9fd940b6d1b760e7a7b9b652625

**Comment by ofthesun9** [comment]
Hello, is it possible to "fix" an already installed system ? I guess we could recreate the zpool.cache and recreate the initramfs ?

**Comment by ofthesun9** [comment]
I did the following:
start the machine
from grub prompt, press e to add break=bottom to the linux cmdline
at initramfs prompt, type: 
```
zpool export rpool
zpool import -d /dev/disk/by-partuuid -R /root rpool
CTRL-D
```
machine finishes the boot
at prompt: 
check zpool status for rpool:
```
sudo zpool status
sudo umount /boot/efi
sudo umount /boot/grub
sudo zpool export bpool
sudo zpool import -d /dev/disk/by-partuuid bpool
sudo mount /boot/efi
sudo mount /boot/grub
```
That did the trick for me

**Comment by jibel** [comment]
Glad it did the trick for you.
That's indeed the way to do it. In case the system didn't boot it can also be done from a live session by importing the pool in /mnt for example by adding -R /mnt to the zpool import command. Then after importing all the pools verify that they are listed in /etc/zfs/zpool.cache (check the output of strings /etc/zfs/zpool.cache) and if it's fine, copy /etc/zfs/zpool.cache to /mnt/etc/zfs/zpool.cache.
